[[tests]]
name = "Integration tests"
paths = [ "tests/integration/*.futil" ]
cmd = "./target/debug/futil {} -l ./primitives/std.lib"

[[tests]]
name = "Automatic Par tests"
paths = [ "tests/automatic-par/*.futil" ]
cmd = "./target/debug/futil {} -l ./primitives/std.lib"
