[package]
name = "calyx"
version = "0.1.0"
authors = ["Samuel Thomas <sgt43@cornell.edu>", "Kenneth Fang <kwf37@cornell.edu>"]
edition = "2018"
build = false
# build = "build.rs"

[dependencies]
structopt = "~0.3"
quickcheck = "0.9.0"
petgraph = "~0.4"
better-panic = "~0.2"
pretty = "~0.9"
sexpy = "~0.5"
itertools = "~0.7"
bumpalo = "3.2.0"

# [build-dependencies]
# clap = "2.33"
# structopt = "~0.3"
