name: Rust

on:
  push: 
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: |
        cd calyx
        cargo build --verbose
    - name: Lint
      run: |
        cd calyx
        cargo clippy --verbose
    - name: Run tests
      run: |
        cd calyx
        cargo test --verbose
